name: Vanderlan Teste
on: push
jobs:
  snik:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ 7827f8c6-8467-4b00-a119-5943a2cafaef }}
